spring:
  data:
    mongodb:
      username: kiran
      password: kiran
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offser-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.kiran.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.kiran.ecommerce.notification.PaymentNotificationRequest
  mail:
    host: localhost
    port: 1025
    username: kirankumarparasa9996@gmail.com
    password: 9396669996
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040




